---
- name: Remove default nginx vhost config file (if configured).
  file:
    path: "{{ nginx_default_vhost_path }}"
    state: absent
  when: nginx_remove_default_vhost
  notify: restart nginx


- debug: var=item.server_name
  with_items: nginx_vhosts

- name: Add managed vhost config file (if any vhosts are configured).
  template:
    src: vhosts.j2
    dest: "{{ nginx_vhost_path }}/{{ item }}.conf"
    mode: 0644
  with_items: "{{ nginx_vhosts }}"
  when: nginx_vhosts|length > 0
  notify: restart nginx

- name: Remove managed vhost config file (if no vhosts are configured).
  file:
    path: "{{ nginx_vhost_path }}/{{ item }}.conf"
    state: absent
  with_items: "{{ nginx_vhosts }}"
  when: nginx_vhosts|length == 0
  notify: restart nginx
